language: node_js

node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: $AWS_S3_BUCKET
  local-dir: build
  on:
    branch: tools/travisci
