version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install yarn command
      - npm install --global yarn

      # Install project dependencies
      - yarn

  pre_build:
    commands:
      # Testing
      - yarn test -- --watchAll=false

  build:
    commands:
      # Build project
      - yarn build

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  files:
    - "**/*"
  base-directory: build
